# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-20 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuid', models.IntegerField(db_column='menuId', primary_key=True, serialize=False)),
                ('menuname', models.CharField(db_column='menuName', max_length=50)),
                ('menuprice', models.IntegerField(db_column='menuPrice')),
                ('menuparentid', models.IntegerField(db_column='menuParentId')),
            ],
            options={
                'managed': False,
                'db_table': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('sellid', models.BigIntegerField(db_column='sellId', primary_key=True, serialize=False)),
                ('sellitem', models.IntegerField(db_column='sellItem')),
                ('sellquantity', models.IntegerField(db_column='sellQuantity')),
                ('selldatetime', models.DateTimeField(blank=True, db_column='sellDatetime', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Sell',
            },
        ),
    ]
